config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"                   #トップページを表示セルルーティング                                                                                                                                       
  resources :users, only: [:edit, :update] #ユーザー編集に必要なルーティングは、editとupdateなので、ユーザー編集に必要なルーティングは、editとupdate                                                           
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create] #今回の場合、ネストをすることにより、roomsが親で、messagesが子という親子関係になるので、チャットルームに属しているメッセージという意味になります。これによって、メッセージに結びつくルームのidの情報を含んだパスを、受け取れるようになります。
  end#チャットルームの削除機能を実装するために、resources :roomsにdestroyアクションのルーティングを追記します。

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :room
  belongs_to :user
  has_one_attached :image #各レコードとファイルを1対1の関係で紐づけるメソッドです。has_one_attachedメソッドを記述したモデルの各レコードは、それぞれ1つのファイルを添付できます。

  validates :content, presence: true, unless: :was_attached?  #Messageモデルに、 validates :content, presence: trueを追記しましょう。#「content」カラムに、presence: trueを設けることで、空の場合はDBに保存しないというバリデーションを設定しています。
  
  def was_attached?
    self.image.attached?
  end
end
#validatesのunlessオプションにメソッド名を指定することで、「メソッドの返り値がfalseならばバリデーションによる検証を行う」という条件を作っています。

#指定されたwas_attached?メソッドは、self.image.attached?という記述によって、画像があればtrue、なければfalseを返す仕組みです。

#これにより、画像が存在しなければテキストが必要となり、画像があればテキストは不要になりました。

app/models/room.rb
class Room < ApplicationRecord
  #MessageモデルとRoomUserモデルにdependent: :destroyを記述します。
  #dependentオプションに:destroyを指定した場合、Room（親モデル）が削除されたときに、関連付けしているMessage（子モデル）とRoomUser（子モデル）も削除されます。
  #これで、roomを削除したとき、roomに関連するmessagesテーブルのレコードとroom_usersテーブルのレコードも、一緒に削除されるように設定できました。
  has_many :room_users, dependent: :destroy#1つのチャットルームには、2人のユーザーが存在します。
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
  validates :name, presence: true #チャットルームを新規作成するにあたって「ルーム名」は必ず必要なので、上記のバリデーションは「ルーム名が存在（presence）している場合のみ作成可（true）」という意味です。

end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user #どのユーザーがどのチャットルームに参加しているかを管理するのが、中間テーブルである「room_userテーブル」となります。

   #チャットルームを新規作成するにあたって「ルーム名」は必ず必要なので、上記のバリデーションは「ルーム名が存在（presence）している場合のみ作成可（true）」という意味です。
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :room_users #1人のユーザーは複数のチャットルームに参加出来ます。
has_many :rooms, through: :room_users
has_many :messages

validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller? #全てのアクションが実行される前に、 before_action :configure_permitted_parameters, if: :devise_controller?が実行されることになります。deviseのコントローラーから呼び出された場合は、configure_permitted_parametersメソッドが呼ばれます
 
  private
  def  configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) #deviseをインストールすることでdevise_parameter_sanitizerメソッドが使えるようになります。deviseでユーザー登録をする場合に使用でき、「特定のカラムを許容する」メソッドです。今回は「nameカラム」を追加したので、このメソッドを使用し、「name」キーの内容の保存をpermitメソッドで許可しています。
    
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new #@messageには、Message.newで生成した、Messageモデルのインスタンス情報を代入します。
    @room = Room.find(params[:room_id]) #@roomには、Room.find(params[:room_id])と記述することで、paramsに含まれているroom_idを代入します。 紐解いて説明すると、直前の問題にあった通りルーティングをネストしているため/rooms/:room_id/messagesといったパスになります。 パスにroom_idが含まれているため、paramsというハッシュオブジェクトの中に、room_idという値が存在しています。そのため、params[:room_id]と記述することでroom_idを取得できます。
    @messages = @room.messages.includes(:user) #一覧画面で表示するメッセージ情報を取得するチャットルームに紐付いている全てのメッセージ（@room.messages）を@messagesと定義します。 そして、一覧画面で表示するメッセージ情報には、ユーザー情報も紐付いて表示されます。この場合、メッセージに紐付くユーザー情報の取得に、メッセージの数と同じ回数のアクセスが必要になるので、N+1問題が発生します。その場合は、includesメソッドを使用して、解消しましょう。全てのメッセージ情報に紐づくユーザー情報を、includes(:user)と記述をすることにより、ユーザー情報を1度のアクセスでまとめて取得することができます。
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save#createアクション内に、メッセージを保存できた場合とできなかった場合で条件分岐の処理を行います。@message.saveでメッセージの保存に成功した場合、redirect_toメソッドを用いてmessagesコントローラーのindexアクションに再度リクエストを送信し、新たにインスタンス変数を生成します。これによって保存後の情報に更新されます。メッセージの保存に失敗した場合、renderメソッドを用いてindexアクションのindex.html.erbを表示するように指定しています。このとき、indexアクションのインスタンス変数はそのままindex.html.erbに渡され、同じページに戻ります。
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user) #一覧画面で表示するメッセージ情報を取得するまた、投稿に失敗したときの処理にも、同様に@messagesを定義しました。renderを用いることで、投稿に失敗した@messageの情報を保持しつつindex.html.erbを参照することができます（この時、indexアクションは経由しません）。しかしながら、そのときに@messagesが定義されていないとエラーになってしまいます。そこで、indexアクションと同様に@messagesを定義する必要があります。
      render :index
    end
  end  #messagesコントローラーにcreateアクションを定義します。でチャットルームに紐づいたメッセージのインスタンスを生成し、message_paramsを引数にして、privateメソッドを呼び出します。その値を@messageに代入し、saveメソッドでメッセージの内容をmessagesテーブルに保存します。
    
  
  private

  def message_params#privateメソッドとしてmessage_paramsを定義し、メッセージの内容(content)をmessagesテーブルへ保存できるようにします。パラメーターの中に、ログインしているユーザーのidと紐付いている、メッセージの内容(content)を受け取れるように許可します。
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index #トップページを表示させる処理
  end

  def new
    @room = Room.new  #チャットルームの新規作成なので「new」アクションを定義します。また、form_withに渡す引数として、値が空のRoomインスタンスを@roomに代入しています
  end

  def create #ここでは、保存が成功したかどうかで処理を分岐しています。 成功した場合はredirect_toメソッドでルートパスにリダイレクトし、 失敗した場合はrenderメソッドでrooms/new.html.erbのページを表示しています。
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy #次に、roomsコントローラーにdestroyアクションを定義します。どのチャットルームを削除するのかを特定する場合は、Room.find(params[:id])を使用して、削除したいチャットルームの情報を取得します。destroyアクションは、削除するだけなのでビューの表示は必要はありません。 そのため、インスタンス変数ではなく変数としてroomを定義し、destroyメソッドを使用します。destroyメソッドが実行されたら、root（roomsのindex）にリダイレクトする記述をします。
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit #users_controller.rbに、editアクションを定義します。
    # editアクションでは、ビューファイルを表示するだけなので、アクションの定義のみになります。
  end

  def update #Userモデルの更新を行うupdateアクションをusersコントローラーに定義しましょう。
    if current_user.update(user_params)#current_user.updateに成功した場合、root（チャット画面）にリダイレクトします
      redirect_to root_path
    else #失敗した場合、render :editとeditのアクションを指定しているため、editのビューが表示されます。
      render :edit
    end
  end #そして、ユーザー情報が格納されているcurrent_userメソッドを使用して、ログインしているユーザーの情報を更新します。

  private

  def user_params #ストロングパラメーターを使用し、user_paramsを定義します。
    params.require(:user).permit(:name, :email)
  end #user_paramsの中でpermitメソッドを使用し、「name」と「email」の編集を許可します。
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %><!--チャットルーム名の情報は、すでにコントローラーの@roomで取得できているため、_main_chat.html.erbを以下のように編集しましょう。-->
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
       <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
   <!--「rails routes」コマンドを実行すると、roomsコントローラーのdestroyアクションに対応するPrefixは、roomということが分かります。
    したがって、削除のパスはroom_pathとなります。
    削除するチャットルームを区別するために、定義している@roomを引数にし、room_path(@room)と指定しましょう。
    HTTPメソッドのdeleteを指定すると、roomsコントローラーのdestroyアクションが実行されます。

    destroyアクションが実行されると、roomを削除することができます。
    最後に、roomを削除したときに、そのroomに関連する情報も削除されるように設定します。-->
   </div>
  </div>
</div>
<div class="messages">
  <%= render partial: 'message', collection: @messages %><!--このように記述することで、_message.html.erbを部分テンプレートとして、読み込むことができます。-->
</div>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %><!--messagesテーブルのuser_idに紐付いているユーザー名を、user.nameと記述することで取得しています。-->
    </div>
    <div class="message-date">
      <%= l message.created_at %><!--messagesテーブルのcreated_atカラムから、投稿した時刻を取得しています。ただし、現段階では日本基準の時刻ではありません。-->
    </div><!--applcation.rbのファイルとja.ymlは作成編集した後にこの l メソッドを記述することで指定時刻が表示される-->
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %><!--messagesテーブルのcontentカラムから、メッセージの内容を取得しています。-->
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %> 
    <!--この記述によって、画像を表示できます。
しかし、このままの記述では、画像が存在しない場合でも、画像を表示する記述が読み込まれて、エラーを引き起こしてしまいます。
この問題を解決するために、メッセージに画像が添付されているかをチェックするattached?というメソッドを使用します。-->
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %> <!--ログインしているユーザーの編集をするため 、edit_user_path(current_user)と指定しますcurrent_user.nameは、ログインしているユーザー名ですユーザー名をクリックすると、usersコントローラーのeditアクションが実行され、編集ページに遷移できます。-->
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %><!--rails routesコマンドで新規作成チャットルームのprifixを確認する-->
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room)%> <!--これによって、メッセージに結びつくルームのidの情報を含んだパスを、受け取れるようになります。したがって、チャットルーム名をクリックすると、messagesコントローラーのindexアクションが実行され、チャットルームのページに遷移できます。-->
      </div>
    </div>
  <% end %>
</div>
<!--・サイドバー下部に、現在ログイン中のユーザーが持っているすべてのチャットルーム名を表示されている
サイドバー下部の実装にはeach文を使用しましょう-->
<!--チャットルームは複数作成出来るので、「eachメソッド」を使って全てのチャットルームに対して同じ処理を繰り返し実行します。
今回でしたら、「チャットルーム名を表示する」という処理を繰り返し実行しています。

2行目の 「|room|」の部分は変数名なので命名規則はないですが、今回は分かりやすいように「room」としています。
また、5行目のroom.nameの「name」は、roomsテーブルのカラム名となります。-->

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>
<!--サイドバーのみの表示となるようにindexファイルを作成しましょう-->

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      <select name="room[user_ids][]"><!--19行目と２３行目select要素のname属性にroom[user_ids][]を指定し、option要素のvalue属性にuser.idを指定しました。このように記述することで、これまでとは異なる形でパラメーターが送信されるため、paramsは以下のようになります。管理機能のカリキュラムを見よう-->
          <option>チャットするユーザーを選択してください</option>
          <!--where.not(id: current_user.id)と記述することで現在ログインしているユーザー名を表示させない-->
            <% User.where.not(id: current_user.id).each do |user| %> <!--ビューファイル上で、DBに管理されているユーザーすべてのレコードをUserクラスから取得して、それぞれ1つずつユーザー名を表示させる実装を行います。-->
              <option value=<%= user.id %>><%= user.name %></option>
            <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id  %>> <!--この記述で、現在ログイン中のユーザーが持つidをparamsに含めることができますroom[user_ids]に2種類のユーザーidを格納することができました。。-->
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>